# --- Conversation States (Only for multi-step processes) ---
(
    ADMIN_MAIN_MENU,
    # Plan Management
    ADMIN_PLAN_MENU, ADMIN_PLAN_AWAIT_NAME, ADMIN_PLAN_AWAIT_DESC,
    ADMIN_PLAN_AWAIT_PRICE, ADMIN_PLAN_AWAIT_DAYS, ADMIN_PLAN_AWAIT_GIGABYTES,
    ADMIN_PLAN_EDIT_MENU, ADMIN_PLAN_EDIT_AWAIT_VALUE,
    # Settings Management
    SETTINGS_MENU, SETTINGS_AWAIT_TRIAL_DAYS, SETTINGS_AWAIT_PAYMENT_TEXT, SETTINGS_AWAIT_USD_RATE, SETTINGS_AWAIT_GATEWAY_API, SETTINGS_AWAIT_SIGNUP_BONUS,
    # User Purchase Flow
    SELECT_PLAN, AWAIT_PAYMENT_SCREENSHOT, AWAIT_DISCOUNT_CODE,
    # Wallet User Flow
    WALLET_AWAIT_AMOUNT_GATEWAY, WALLET_AWAIT_AMOUNT_CARD, WALLET_AWAIT_CARD_SCREENSHOT, WALLET_AWAIT_AMOUNT_CRYPTO, WALLET_AWAIT_CRYPTO_SCREENSHOT,
    # Admin Stats
    ADMIN_STATS_MENU,
    # Message & Button Editor
    ADMIN_MESSAGES_MENU, ADMIN_MESSAGES_SELECT, ADMIN_MESSAGES_EDIT_TEXT,
    ADMIN_BUTTON_ADD_AWAIT_TEXT, ADMIN_BUTTON_ADD_AWAIT_TARGET,
    ADMIN_BUTTON_ADD_AWAIT_URL, ADMIN_BUTTON_ADD_AWAIT_ROW, ADMIN_BUTTON_ADD_AWAIT_COL,
    # New Message Creation
    ADMIN_MESSAGES_ADD_AWAIT_NAME, ADMIN_MESSAGES_ADD_AWAIT_CONTENT,
    # Card Management
    ADMIN_CARDS_MENU, ADMIN_CARDS_AWAIT_NUMBER, ADMIN_CARDS_AWAIT_HOLDER,
    # Wallet Management (Admin)
    ADMIN_WALLET_MENU, ADMIN_WALLET_ADJUST_AWAIT_USER, ADMIN_WALLET_ADJUST_AWAIT_AMOUNT,
    # Wallet Management
    ADMIN_WALLETS_MENU, ADMIN_WALLETS_AWAIT_ASSET, ADMIN_WALLETS_AWAIT_CHAIN, ADMIN_WALLETS_AWAIT_ADDRESS, ADMIN_WALLETS_AWAIT_MEMO,
    # Payment Method Selection
    SELECT_PAYMENT_METHOD,
    # Broadcast
    BROADCAST_SELECT_AUDIENCE, BROADCAST_SELECT_MODE, BROADCAST_AWAIT_MESSAGE,
    # Renewal Flow States
    RENEW_SELECT_PLAN, RENEW_AWAIT_PAYMENT, RENEW_AWAIT_DISCOUNT_CODE,
    # Discount Code Management
    DISCOUNT_MENU, DISCOUNT_AWAIT_CODE, DISCOUNT_AWAIT_PERCENT,
    DISCOUNT_AWAIT_LIMIT, DISCOUNT_AWAIT_EXPIRY,
    # Multi-Panel Management
    ADMIN_PANELS_MENU, ADMIN_PANEL_AWAIT_NAME, ADMIN_PANEL_AWAIT_TYPE, ADMIN_PANEL_AWAIT_URL,
    ADMIN_PANEL_AWAIT_SUB_BASE, ADMIN_PANEL_AWAIT_TOKEN, ADMIN_PANEL_AWAIT_USER, ADMIN_PANEL_AWAIT_PASS,
    # Backup
    BACKUP_CHOOSE_PANEL,
    # Panel Inbound Management (NEW)
    ADMIN_PANEL_INBOUNDS_MENU, ADMIN_PANEL_INBOUNDS_AWAIT_PROTOCOL, ADMIN_PANEL_INBOUNDS_AWAIT_TAG,
    # Support
    SUPPORT_AWAIT_TICKET, ADMIN_AWAIT_TICKET_REPLY,
    # Reseller
    RESELLER_AWAIT_UPLOAD, ADMIN_RESELLER_MENU, ADMIN_RESELLER_AWAIT_VALUE,
) = range(74)